title: Hans Elliott
url: "https://hans-elliott99.github.io/"
baseurl: "/home"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/hans-elliott99"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/home/"
 - name: "Resume"
   link: "Resume.html"
